# Generated by Django 5.1.4 on 2025-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_record_agent_name_alter_record_agent_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch', models.CharField(default='', max_length=255)),
                ('car_model', models.CharField(default='', max_length=200)),
                ('plate_number', models.CharField(default='', max_length=200)),
                ('car_color', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
