# Generated by Django 5.1.4 on 2025-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_allvehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='allvehicles',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='allvehicles',
            name='hire_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allvehicles',
            name='images',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
