# Generated by Django 5.1.4 on 2025-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyElectric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hire_amount', models.FloatField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MySuvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hire_amount', models.FloatField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MyVans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hire_amount', models.FloatField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=250)),
            ],
        ),
    ]
