# Generated by Django 5.1.4 on 2025-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_myelectric_mysuvs_myvans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='rent/')),
                ('milage', models.FloatField(default=0)),
                ('hire_amount', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('settings', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
                ('car_name', models.CharField(max_length=250)),
            ],
        ),
    ]
