# Generated by Django 5.1.4 on 2025-02-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_forrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forrent',
            name='hire_amount',
        ),
    ]
