# Generated by Django 5.1.4 on 2025-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_forrent_hire_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('date', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('header', models.CharField(max_length=50)),
                ('story', models.CharField(max_length=250)),
            ],
        ),
    ]
