# Generated by Django 5.1.4 on 2025-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('plate_number', models.CharField(default='', max_length=200)),
                ('vehicle_name', models.CharField(max_length=250)),
                ('vehicle_color', models.CharField(default='', max_length=200)),
                ('vehicle_category', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
                ('hire_amount', models.FloatField(default=0)),
            ],
        ),
    ]
