# Generated by Django 5.1.4 on 2025-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_vehicledetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleDetails',
            new_name='VehicleDetail',
        ),
    ]
