# Generated by Django 5.1.4 on 2025-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_vehicledetails_vehicledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('company_branch', models.CharField(default='', max_length=255)),
                ('car_model', models.CharField(default='', max_length=200)),
                ('plate_number', models.CharField(default='', max_length=200)),
                ('car_color', models.CharField(default='', max_length=200)),
                ('agent_name', models.CharField(default='', max_length=200)),
                ('agent_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ForRent',
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='milage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='settings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
