# Generated by Django 5.1.4 on 2025-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rentedvehicle_delete_forrent_vehicledetail_milage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
