# Generated by Django 5.1.4 on 2025-03-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_vehicledetail_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_category',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
