# Generated by Django 5.1.4 on 2025-03-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_category_alter_vehicledetail_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
