# Generated by Django 5.1.4 on 2025-03-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_vehicledetail_vehicle_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCars',
        ),
        migrations.DeleteModel(
            name='MyElectric',
        ),
        migrations.DeleteModel(
            name='MySuvs',
        ),
        migrations.DeleteModel(
            name='MyVans',
        ),
    ]
