# Generated by Django 4.2.20 on 2025-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_delete_mycars_delete_myelectric_delete_mysuvs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
