# Generated by Django 4.2.20 on 2025-03-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_transaction_rentedvehicle_hire_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RemoveField(
            model_name='rentedvehicle',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='rentedvehicle',
            name='agent_number',
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
