# Generated by Django 4.2.20 on 2025-03-20 11:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_milage_vehicledetail_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 20, 11, 16, 49, 627602, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='hire_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
