# Generated by Django 4.2.20 on 2025-03-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_phone_rentavehicle_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentAVehicle',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='checkout_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='national_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
