# Generated by Django 4.2.20 on 2025-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_delete_rentavehicle_remove_transaction_checkout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='creation_date',
        ),
    ]
