# Generated by Django 4.2.20 on 2025-03-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_transaction_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
