# Generated by Django 4.2.20 on 2025-03-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_rename_phone_number_transaction_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
