# Generated by Django 4.2.20 on 2025-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_rename_phone_transaction_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
