# Generated by Django 4.2.20 on 2025-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_transaction_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plate_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionCode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vehicle_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vehicle_name',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
