# Generated by Django 4.2.20 on 2025-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_transaction_plate_number_transaction_transactioncode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vehicle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
