# Generated by Django 4.2.20 on 2025-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_alter_transaction_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hire_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
