# Generated by Django 4.2.20 on 2025-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_transaction_hire_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hire_amount',
            field=models.IntegerField(default=0),
        ),
    ]
