# Generated by Django 4.2.20 on 2025-03-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_transaction_hire_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hire_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
